### ISSUE TITLE
🐛 Nightly builds of @biomejs/cli-* don't publish CLI binary

### ISSUE THREAD

**Issue by benjamincburns** [biomejs/biome#3804]
It would appear that none of the published NPM packages for the v1.8.4 nightly builds of `@biomejs/cli-linux-x64` include the `biome` binary, which I imagine is probably the only reason this package is published at all.

- [@biomejs/cli-linux-x64@v1.8.4-nightly.d079e53 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.d079e53?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.4-nightly.bd1d0c6 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.bd1d0c6?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.4-nightly.a579bf7 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.a579bf7?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.3 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.3?activeTab=code)
- [@biomejs/cli-linux-x64@1.7.4-nightly.125f34b files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.7.4-nightly.125f34b?activeTab=code)

### What happened?

Run the following on any x86 linux host:

```
npx @biomejs/biome@nightly
```

This results in the following error, or similar: `Error: Cannot find module '@biomejs/cli-linux-x64/biome'`

### Expected result

It should work as normal.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by benjamincburns** [comment]
I haven't checked the other platform-specific packages exhaustively, but so far for the latest nightly release I haven't found a CLI package that actually included the nightly.

**Comment by benjamincburns** [comment]
Trying to track down the cause. It would seem that [the step in `generate-packages.mjs` that copies binaries into the correct location for packaging](https://github.com/biomejs/biome/blob/d079e53e15cfd0ce95f018713b8f38d7a5341725/packages/%40biomejs/biome/scripts/generate-packages.mjs#L61-L65) is failing silently due to a change that was introduced in #3423. Otherwise I'd expect to see `Copy binary XYZ` in [the logs for the publish step for the most recent nightly](https://github.com/biomejs/biome/actions/runs/10481179692/job/29030629867#step:7:20), as was the case in [the publish build for v1.8.3](https://github.com/biomejs/biome/actions/runs/9697679396/job/26763571306#step:7:28). That won't be the root cause, but it will be why it has gone unnoticed.

I may be misunderstanding the intent behind that code, but I think the problem is that `generate-packages.mjs` is gating the binary copy step on whether the `binaryTarget` path exists, but `binaryTarget` appears to be the full path to the copy destination, including the intended filename for the binary. If it hasn't been copied to that path yet, it won't exist. One way to fix it would be to check if `path.dirname(binaryTarget)` exists, but that will still fail silently. Personally I think it'd be better to just remove the `fs.fileExistsSync` check and if this causes failures due to the target directory not exiting, address that problem more directly.
